<template>
  <div class="container h-full text-gray-500 dark:text-gray-200">
    <p class="texl:xl md:text-3xl text-gray-600 dark:text-gray-200 text-center font-bold mb-5">
      Here are some of the personal projects I have worked on
    </p>
    <div class="flex flex-col mt-20 gap-20">
      <div  class="min-w-full flex flex-col md:flex-row justify-evenly items-center gap-4">
        <img src="../assets/screenshot1.png" alt="screenshot" class="max-h-[200px] md:max-h-[350px] max-w-[200px] md:max-w-[350px] h-auto w-auto flex-[0_0_50%]">
        <div class="min-w-1/2 text-start bg-white bg-opacity-40 dark:bg-gray-900 shadow rounded-xl p-6 relative flex-[0_0_50%]">
          <p class="text-xl font-bold text-center mb-4">Hefty</p>
          <p>Displays product data retrieved from dummyjson</p>
          <p class="text-sm font-light my-4">Vue</p>
          <a :href="project3" target="_blank" rel="noopener noreferrer"><v-icon name="md-arrowforward" class="absolute bottom-5 right-10 p-4 hover:translate-x-2 duration-500" /></a>
        </div>
      </div>
      <div></div>
      <div  class="min-w-full flex flex-col md:flex-row justify-evenly items-center gap-4">
        <img src="../assets/screenshot2.png" alt="screenshot" class="max-h-[200px] md:max-h-[350px] max-w-[200px] md:max-w-[350px] h-auto w-auto flex-[0_0_50%]">
        <div class="min-w-1/2 text-start bg-white bg-opacity-40 dark:bg-gray-900 shadow rounded-xl p-6 relative flex-[0_0_50%]">
          <p class="text-xl font-bold text-center mb-4">User Auth</p>
          <p>Displays users based on data generated by the RandomUser API and data stored as a Firestore collection</p>
          <p class="text-sm font-light my-4">React Firebase Firestore</p>
          <a :href="project3" target="_blank" rel="noopener noreferrer"><v-icon name="md-arrowforward" class="absolute bottom-5 right-10 p-4 hover:translate-x-2 duration-500" /></a>
        </div>
      </div>
      <div></div>
      <div class="min-w-full flex flex-col md:flex-row justify-evenly items-center gap-4">
        <img src="../assets/screenshot3.png" alt="screenshot" class="max-h-[200px] md:max-h-[350px] max-w-[200px] md:max-w-[350px] h-auto w-auto flex-[0_0_50%]">
        <div class="min-w-1/2 text-start bg-white bg-opacity-40 dark:bg-gray-900 shadow rounded-xl p-6 relative flex-[0_0_50%]">
          <p class="text-xl font-bold text-center mb-4">Fake User Auth</p>
          <p>Displays a table of users using a mock list generated by the RandomUser API</p>
          <p class="text-sm font-light my-4">React</p>
          <a :href="project3" target="_blank" rel="noopener noreferrer"><v-icon name="md-arrowforward" class="absolute bottom-5 right-10 p-4 hover:translate-x-2 duration-500" /></a>
        </div>
      </div>
    </div>
  </div>
</template>



<script lang="ts">
import { defineComponent } from 'vue';
import SkillTracks from '../components/SkillTracks.vue';


export default defineComponent({
  data() {
    return {
      project1: "https://tolu-vue-exam.netlify.app",
      project2: "https://peppy-palmier-397c98.netlify.app",
      project3: "https://tangerine-pika-8bffea.netlify.app",
    }
  },
  components: {
    SkillTracks,
  },
});
</script>